steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/checkersgame-a3b92/cloud-run-source-deploy/checkersapi/checkersapi:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/checkersgame-a3b92/cloud-run-source-deploy/checkersapi/checkersapi:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'checkersapi', '--image', 'us-central1-docker.pkg.dev/checkersgame-a3b92/cloud-run-source-deploy/checkersapi/checkersapi:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--quiet']
options:
  logging: CLOUD_LOGGING_ONLY
